action_id: trunk-share-with-everyone
date: 2023-06-23 23:36:21
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1687563381
full_timestamp:
  nanos: 435792000
  seconds: 1687563381
trunk_version: 1.11.1
